package com.lsn.lib_db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lsn.lib_db.bean.BHttpCache;

import com.lsn.lib_db.dao.BHttpCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bHttpCacheDaoConfig;

    private final BHttpCacheDao bHttpCacheDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bHttpCacheDaoConfig = daoConfigMap.get(BHttpCacheDao.class).clone();
        bHttpCacheDaoConfig.initIdentityScope(type);

        bHttpCacheDao = new BHttpCacheDao(bHttpCacheDaoConfig, this);

        registerDao(BHttpCache.class, bHttpCacheDao);
    }
    
    public void clear() {
        bHttpCacheDaoConfig.clearIdentityScope();
    }

    public BHttpCacheDao getBHttpCacheDao() {
        return bHttpCacheDao;
    }

}
